fixed pre-commit

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,17 +1,16 @@
 #!/bin/sh
 
-# vas al root directory del proyecto
-#cd "$(git rev-parse --show-toplevel)" || exit
+# vas al project root
+cd "$(git rev-parse --show-toplevel)" || exit
 
-# Formatea el codigo
-./gradlew formatApply
-git add . -u #agrega todos los elementos versionados y sin commitear (producto del formateo anterior)
+# Corre los tests
+./gradlew test
 
-# Corre los tests y check
-./gradlew build
+# verifica que el código esté formateado bien
+./gradlew lintCheck
 
 # Si falla, rechaza el push
 if [ $? -ne 0 ]; then
-  echo "Pre-push checks failed. Push cancelled."
+  echo "Pre-push checks failed. Push aborted."
   exit 1
 fi
